name: Kotlin Multiplatform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35

      - name: Build Android
        run: ./gradlew assembleDebug

      - name: Test Android
        run: ./gradlew testDebugUnitTest

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build iOS
        run: ./gradlew iosX64Binaries

      - name: Test iOS
        run: ./gradlew iosTest

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build macOS
        run: ./gradlew macosX64Binaries

      - name: Test macOS
        run: ./gradlew macosTest

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev

      - name: Build Linux
        run: ./gradlew linuxX64Binaries

      - name: Test Linux
        run: ./gradlew linuxTest

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up MSVC
        run: |
          choco install visualstudio2019community
          choco install visualstudio2019buildtools
          choco install visualstudio2019-workload-vctools

      - name: Build Windows
        run: ./gradlew mingwX64Binaries

      - name: Test Windows
        run: ./gradlew mingwTest

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Build WASM
        run: ./gradlew wasm32Binaries

      - name: Test WASM
        run: ./gradlew wasmTest
